import {BiAlignLeft} from 'react-icons/bi';

const routesConfig = [
  {
    id: 'app',
    title: 'Sample',
    messageId: 'sidebar.sample',
    type: 'group',
    children: [
      {
        id: 'college',
        title: 'College',
        messageId: 'College',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/college-masters',
      },
      {
        id: 'department',
        title: 'Department',
        messageId: 'Department',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/department-masters',
      },

      {
        id: 'course',
        title: 'Course',
        messageId: 'Course',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/course-masters',
      },

      {
        id: 'category',
        title: 'Categories',
        messageId: 'Category',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/category-masters',
      },
      {
        id: 'sub-category',
        title: 'Sub-Category',
        messageId: 'Sub-Category',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sub-category-masters',
      },
      {
        id: 'subject',
        title: 'Subject',
        messageId: 'Subject',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/subject-masters',
      },
      {
        id: 'sub-subject',
        title: 'Sub-Subject',
        messageId: 'Sub-Subject',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sub-subject-masters',
      },
      {
        id: 'topic',
        title: 'Topic',
        messageId: 'Topic',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/topic-masters',
      },
      {
        id: 'sub-topic',
        title: 'Sub-Topic',
        messageId: 'Sub-Topic',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sub-topic-masters',
      },
      {
        id: 'question-type-category',
        title: 'Question-Type Category',
        messageId: 'Question-Type Category',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/question-type-category-masters',
      },
      {
        id: 'question-type',
        title: 'Question-Type',
        messageId: 'Question-Types',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/question-type-masters',
      },
      {
        id: 'difficulty-type',
        title: 'Difficulty-Type',
        messageId: 'Difficulty-Types',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/difficulty-type-masters',
      },
      {
        id: 'questions',
        title: 'Questions',
        messageId: 'Questions',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/question-masters',
      },
      {
        id: 'question-bank',
        title: 'Question Bank',
        messageId: 'Question Bank',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/question-bank-masters',
      },
      {
        id: 'question-blue-print',
        title: 'Question Blue Print',
        messageId: 'Question Blue Print',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/question-blue-print-masters',
      },
      {
        id: 'exam',
        title: 'Exam',
        messageId: 'Exams',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/exam-masters',
      },
    ],
  },
];
export default routesConfig;
